// import TrackPlayer, { Capability, Event } from 'react-native-track-player';

// export const setupPlayer = async () => {
//   try {
//     await TrackPlayer.setupPlayer();
//     await TrackPlayer.updateOptions({
//       stopWithApp: true,
//       capabilities: [
//         Capability.Play,
//         Capability.Pause,
//         Capability.SkipToNext,
//         Capability.SkipToPrevious,
//         Capability.Stop,
//       ],
//       compactCapabilities: [
//         Capability.Play,
//         Capability.Pause,
//         Capability.SkipToNext,
//         Capability.SkipToPrevious,
//       ],
//     });
//   } catch (error) {
//     console.error('Error setting up TrackPlayer:', error);
//   }
// };

// export const playbackService = async function () {
//   TrackPlayer.addEventListener(Event.RemotePlay, () => TrackPlayer.play());
//   TrackPlayer.addEventListener(Event.RemotePause, () => TrackPlayer.pause());
//   TrackPlayer.addEventListener(Event.RemoteNext, () =>
//     TrackPlayer.skipToNext(),
//   );
//   TrackPlayer.addEventListener(Event.RemotePrevious, () =>
//     TrackPlayer.skipToPrevious(),
//   );
//   TrackPlayer.addEventListener(Event.RemoteStop, () => TrackPlayer.destroy());

//   // Add more event listeners as needed for background playback, audio focus, etc.
// };

// export const addChapterToQueue = async (
//   chapterId: string,
//   chapterTitle: string,
//   _chapterContent: string,
// ) => {
//   await TrackPlayer.add({
//     id: chapterId,
//     url: 'file://' + chapterId, // Placeholder, actual audio will be generated by TTS
//     title: chapterTitle,
//     artist: 'Modern Fleet App',
//     artwork: undefined, // Can add artwork later
//   });
// };

// export const playChapter = async (
//   chapterId: string,
//   chapterTitle: string,
//   chapterContent: string,
// ) => {
//   await addChapterToQueue(chapterId, chapterTitle, chapterContent);
//   await TrackPlayer.play();
// };

// export const togglePlayback = async (playbackState: any) => {
//   if (playbackState === 'playing') {
//     await TrackPlayer.pause();
//   } else {
//     await TrackPlayer.play();
//   }
// };

// Temporary stub exports to avoid import errors
export const setupPlayer = async () => {
  console.log('TrackPlayer temporarily disabled');
};

export const playbackService = async function () {
  console.log('TrackPlayer service temporarily disabled');
};

export const addChapterToQueue = async (
  _chapterId: string,
  _chapterTitle: string,
  _chapterContent: string,
) => {
  console.log('TrackPlayer addChapterToQueue temporarily disabled');
};

export const playChapter = async (
  _chapterId: string,
  _chapterTitle: string,
  _chapterContent: string,
) => {
  console.log('TrackPlayer playChapter temporarily disabled');
};

export const togglePlayback = async (_playbackState: unknown) => {
  console.log('TrackPlayer togglePlayback temporarily disabled');
};
